const ProviderUrls = {
    'Netflix': 'https://www.netflix.com/ar/',
    'Amazon Prime Video': 'https://www.primevideo.com/',
    'Disney Plus': 'https://www.disneyplus.com/es-ar',
    'Star Plus': 'https://www.starplus.com/es-ar',
    'Max': 'https://www.max.com/ar/es',
    'Apple TV': 'https://tv.apple.com/ar',
    'Apple TV+': 'https://tv.apple.com/ar',
    'Paramount Plus': 'https://www.paramountplus.com/ar/',
    'Claro video': 'https://www.clarovideo.com/ar/',
    'MovistarTV': 'https://tv.movistar.com.ar',
    'Google Play Movies': 'https://play.google.com/store/movies',
    'YouTube': 'https://www.youtube.com/movies',
    'MUBI': 'https://mubi.com/',
    'Curiosity Stream': 'https://curiositystream.com/',
    'VIX': 'https://www.vix.com/',
    'DIRECTV GO': 'https://www.directvgo.com/',
    'DOCSVILLE': 'https://www.docsville.com/',
    'CINE': 'https://play.cine.ar/bienvenida/',
    'Magellan TV': 'https://www.magellantv.com/',
    'WOW Presents Plus': 'https://www.wowpresentsplus.com/',
    'BroadwayHD': 'https://www.broadwayhd.com/',
    'Filmzie': 'https://www.filmzie.com/',
    'Dekkoo': 'https://www.dekkoo.com/',
    'DocAlliance Films': 'https://www.dafilms.com/',
    'OnDemandKorea': 'https://www.ondemandkorea.com/',
    'Hoichoi': 'https://www.hoichoi.tv/',
    'Pluto TV': 'https://pluto.tv/es/',
    'Eventive': 'https://watch.eventive.org/',
    'Cultpix': 'https://cultpix.com/',
    'FilmBox+': 'https://filmbox.com/',
    'Takflix': 'https://takflix.com/',
    'Sun Nxt': 'https://www.sunnxt.com/',
    'Runtime': 'https://www.runtime.tv',
    'Crunchyroll': 'https://www.crunchyroll.com/es',
    'Paramount Plus Apple TV Channel': 'https://www.paramountplus.com/es/',
    'Shahid VIP': 'https://shahid.mbc.net/ar',
    'Univer Video': 'https://www.univervideo.com/',
    'Plex': 'https://www.plex.tv/',
    'Adrenalina Pura Amazon channel': 'https://www.adrenalinapura.com/',
    'Adrenalina Pura Apple TV channel': 'https://www.adrenalinapura.com/',
    'Mercado Play': 'https://www.mercadolibre.com.ar/',
    'TVCortos Amazon Channel': 'https://www.amazon.com/gp/video/storefront/ref=atv_dp_season_select?ie=UTF8&season=1&tag=tv-cortos-20',
    'Jolt Film': 'https://www.jolttv.com/',
    'FOUND TV': 'https://foundtv.com/',
    'BroadwayHD': 'https://www.broadwayhd.com/',
    'JustWatchTV': 'https://www.justwatch.com/ar/',
};

export default ProviderUrls;